export const HOME = "/";
export const PROGRAMS = "/programs";
export const WHY_PUPILO = "/why-pupilo";
export const LEARN_WITH_PUPILO = "/learn-with-pupilo";
export const BLOG = "/blog";
export const INSTA = "https://www.instagram.com/radialcode/";
export const FACEBOOK = "https://www.facebook.com/radialcode/";
export const TIKTOK = "https://www.tiktok.com/about?lang=en";
export const YOUTUBE = "https://www.youtube.com/@radialcode";
export const LINKEDIN = "https://in.linkedin.com/company/radialcode";
export const WHATSAPP = "https://wa.me/+234 098 765 4321";
export const MAIL = "mailto:hello@pupiloinc.com";
export const PHONE = "tel:+234 123 456 7890";